main.go
plugin.go

fix #1 support debug mode.

---

.gitignore
README.md
main.go

Support load configuration from files.

---

README.md
plugin.go

fix tar multiple folder or file.

---

README.md
main.go
plugin.go

remove target folder before upload data.
Fixed #9

Support rm flag

---

README.md
main.go
plugin.go
plugin_test.go

support multiple host

---

README.md
main.go
plugin.go

support multiple target

---

README.md
main.go
plugin.go

Support golang routines

---

.drone.yml
.gitignore
.travis.yml
Makefile
README.md
easyssh/easyssh.go
glide.lock
glide.yaml
main.go

Fix #16 
* upload docker image.
* release tag

Add release tool 

---

easyssh/easyssh.go
main.go
plugin.go

feat: Add timeout flag.

---

plugin.go
plugin_test.go

feat: support wildcard file list.

---

.travis.yml
Makefile
easyssh/easyssh_test.go

test: improve code coverage for easyssh.

---

main.go
plugin.go
plugin_test.go
vendor/github.com/appleboy/easyssh-proxy/easyssh.go
vendor/vendor.json

feat: Support scp files from proxy command.

---

plugin.go

feat: remove temp file if encounter errors.

---

plugin.go
plugin_test.go

add copy error handle.

---

plugin.go
plugin_test.go

update testing for remove single dest file.

---

vendor/github.com/appleboy/easyssh-proxy/Makefile
vendor/github.com/appleboy/easyssh-proxy/README.md
vendor/github.com/appleboy/easyssh-proxy/easyssh.go
vendor/golang.org/x/crypto/ssh/certs.go
vendor/golang.org/x/crypto/ssh/client.go
vendor/golang.org/x/crypto/ssh/client_auth.go
vendor/golang.org/x/crypto/ssh/common.go
vendor/golang.org/x/crypto/ssh/doc.go
vendor/golang.org/x/crypto/ssh/handshake.go
vendor/golang.org/x/crypto/ssh/keys.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/golang.org/x/crypto/ssh/streamlocal.go
vendor/golang.org/x/crypto/ssh/tcpip.go
vendor/vendor.json

fix #58 
related https://github.com/appleboy/easyssh-proxy/issues/16

refactor: HostKeyCallback is the function type used for verifying server

---

plugin.go

Improve scp error message.

---

plugin.go
plugin_test.go

refactor: show errors if set password and key at the same time

---

main.go
plugin.go
plugin_test.go

Remove the specified number of leading path elements.
fix #64

feat: support strip components flag for tar command

---

.drone.yml

upgrade drone config.

---

vendor/github.com/appleboy/easyssh-proxy/Makefile
vendor/github.com/appleboy/easyssh-proxy/easyssh.go
vendor/vendor.json

upgrade easyssh-proxy

---

main.go

Add some ssh env

---

plugin.go
plugin_test.go

feat(ignore): support ignore list

---

.drone.yml
main.go
plugin.go
plugin_test.go

add debug command.

---

plugin.go
plugin_test.go

fix missing exclude files

---

plugin.go

fix partial of #74
See the comment https://github.com/appleboy/drone-scp/issues/74#issuecomment-463689306

fix: remove check username exist.

---

main.go

fix: trigger build fail if error

---

main.go
plugin.go
plugin_test.go

fix https://github.com/appleboy/drone-scp/pull/80

feat(tar): add Overwrite flag

---

go.mod
go.sum
main.go
plugin.go
plugin_test.go

related issue: https://github.com/appleboy/scp-action/issues/15

chore: Support UseInsecureCipher

---

command.go
command_windows.go
plugin.go

ref https://github.com/appleboy/drone-scp/pull/119

chore(command): support windows

---

main.go
plugin.go
plugin_test.go

- Add a `--dereference` flag to use with tar
fix https://github.com/appleboy/drone-scp/issues/112

refactor: add dereference flag

---

command.go
command_test.go

- Add functions for removing and creating files/directories based on the operating system
- Add unit tests for the functions

feat: improve file handling with OS-specific functions and tests

---

DOCS.md

See https://github.com/woodpecker-ci/woodpecker/pull/4871 for more information

docs: add woodpecker compatible metadata
